// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ordhrhnnkfdhqdxvxzmr.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZGhyaG5ua2ZkaHFkeHZ4em1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNDYwODUsImV4cCI6MjA0ODgyMjA4NX0.-GBIBaQjm6W652npt_YThwaQEhXs_SYGZWRqZwfqqxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);